#!/usr/bin/env python3
"""Export numerical supplementary tables from completed reports; no model fitting."""
from pathlib import Path
import csv,json
ROOT=Path(__file__).resolve().parents[2]
HERE=Path(__file__).resolve().parent
ANALYSIS=ROOT/'outputs/analysis'
REVISION=ROOT/'outputs/scientific_revision_20260922'
LATEST=ROOT/'outputs/scientific_revision_20260923'
AUDIT=ROOT/'outputs/scientific_revision_20260925'
MEASUREMENT=REVISION/'measurement'
MEASUREMENT_REPORTS={'patient_mapping_equivalence','representation_benchmark','representation_inference','patient_unit_representation_benchmark','design_power_simulation'}
TOPIC_LABELS=['TIMP1/COL3A1', 'JUNB/DNAJB1', 'COL1A1/COL1A2', 'IGFBP7/IGFBP5', 'TAGLN/ACTA2', 'KRT14/KRT10', 'CFD/APOD', 'DCN/CFD', 'DCD/SAT1', 'IGFBP7/SPARCL1', 'FOS/IGFBP7', 'HLA-DRA/CD74', 'IGFBP7/TAGLN', 'FOS/JUNB', 'DNAJB1/FOS']
def report(n):return json.loads(((MEASUREMENT if n in MEASUREMENT_REPORTS else ANALYSIS)/n/'report.json').read_text())
def esc(x):
 return str(x).replace('&',r'\&').replace('%',r'\%').replace('_',r'\_').replace('#',r'\#')
def historical(n):
 if n=='cohort_metadata/gse165816_patient_unit_remap':return json.loads((MEASUREMENT/'patient_unit_remap/report.json').read_text())
 if n=='representation_benchmark':return report(n)
 return json.loads((ROOT/'outputs'/n/'report.json').read_text())
def probability(x):return f'{float(x):.3g}' if x is not None else '—'
def f(x,n=4):return '—' if x in (None,'') else f'{float(x):.{n}f}'
def table(label,caption,headers,rows,widths,break_before=None):
 col='@{}'+''.join('p{'+str(w)+'mm}' for w in widths)+'@{}'
 header=' & '.join(esc(h) for h in headers)+r' \\'
 # Longtable measures its caption/header and starts only when a row fits.
 # Keep the first and last row pairs together without reserving an estimated
 # table height, which can push otherwise usable content onto another page.
 # break_before starts a continuation page early enough that the last page
 # is not a few orphan rows.
 lines=[]
 for i,row in enumerate(rows):
  if break_before is not None and i==break_before:
   lines.append(r'\pagebreak')
  lines.append(' & '.join(esc(c) for c in row)+(r' \\*' if len(rows)>1 and i in (0,len(rows)-2) else r' \\'))
 body='\n'.join(lines)
 return '\n'.join([r'{\small',r'\begin{longtable}{'+col+'}',r'\caption{'+caption+r'}\label{'+label+r'}\\',r'\toprule',header,r'\midrule\endfirsthead',r'\multicolumn{'+str(len(headers))+r'}{l}{\tablename\ \thetable\ (continued)}\\',r'\toprule',header,r'\midrule\endhead',r'\bottomrule\endfoot',body,r'\end{longtable}',r'}'])
def csvrows(n):
 folder=MEASUREMENT/'tables' if n in {'paper1_representation_inference.csv','paper1_patient_unit_and_anatomy.csv','paper1_representation_cross_method.csv'} else ROOT/'manuscripts/tables'
 return list(csv.DictReader((folder/n).open()))
# Each exported table lives in TeX; no Markdown draft is used by the build.
p2=[]
h=report('human_temporal_flow');d=report('donor_transfer_flow')
rows=[['Pooled time holdout',f(h['all_donors']['standstill']),f(h['all_donors']['predicted']),f(h['all_donors']['noise_floor']),f(h['all_donors']['improvement']*100,2)+'%']]
for name,v in h['leave_one_donor_out'].items():rows.append(['Drop '+name+'; retained pair',f(v['standstill']),f(v['predicted']),f(v['noise_floor']),f(v['improvement']*100,2)+'%'])
for name,v in d['per_donor'].items():rows.append([name+' transfer',f(v['ed_standstill']),f(v['ed_predicted']),f(v['noise_floor']),f(v['improvement']*100,2)+'%'])
p2.append(table('tab:p2folds','Human Wound7 evaluation in GSE241132. ED denotes the empirical energy-distance V-statistic in training-standardized latent space; lower values indicate closer predicted and observed distributions. The pooled row excludes Wound7 globally. Drop-one rows exclude the named donor and evaluate pooled Wound7 only in the two retained donors. Transfer rows instead evaluate the excluded donor after fitting all four time points of the other donors. Improvement is 100 times (stay-still ED minus predicted ED) divided by stay-still ED. Split-half ED uses one seeded target split and is not a confidence limit. Every row is a point estimate; these dependent fits do not create additional donors.',['Evaluation','Stay-still ED','Predicted ED','Split-half ED','Improvement'],rows,[50,28,28,28,31]))
d=report('time_parameterisation')
rows=[[n.replace('_',' '),f(v['t_holdout']),f(v['ed_at_claimed']),f(v['improvement_at_claimed']*100,2)+'%',str(v['diverged'])] for n,v in d['axes_results'].items()]
p2.append(table('tab:p2axes','Historical single-seed four-clock diagnostic under global Wound7 holdout; not the revised paired exact-time comparison. The reference distance is '+f(d['standstill'])+' and the split-half distance is '+f(d['noise_floor'])+'. ED denotes empirical energy distance in training-standardized latent space. Wound7 time is the global transformed coordinate; target distance uses the nearest point of the 60-step Wound1-to-Wound30 scan. Improvement is 100 times gain divided by stay-still distance. The three donors are reused, endpoint draws were not paired across clocks, and the path minimum is not substituted for target error. No interval is shown.',['Time coordinate','Wound7 time','Target ED','Improvement','Diverged'],rows,[41,32,31,32,29]))
clock=json.loads((ROOT/'outputs/scientific_revision_20260925/paired_clock/run/paired_clock/report.json').read_text())
clock_rows=list(csv.DictReader((ROOT/'outputs/scientific_revision_20260925/paired_clock/run/paired_clock/per_donor_seed.csv').open()))
rows=[]
for v in clock['summary']:
 selected=[r for r in clock_rows if r['axis']==v['axis']]
 seed_means=[sum(float(r['flow_ed']) for r in selected if int(r['seed'])==s)/3 for s in (0,1,2)]
 max_delta=max(abs(float(r['flow_ed'])-float(r['refined_flow_ed'])) for r in selected)
 rows.append([v['axis'].replace('_',' '),f(v['flow_ed']),f(min(seed_means))+' to '+f(max(seed_means)),f(v['centroid_ed']),f(v['unchanged_source_ed']),f'{max_delta:.2e}'])
p2.append(table('tab:p2pairedclock',r'Paired exact-time clock audit: four transforms, three seeds, 12 fields, three healthy donors. Each fit uses 8,000 steps, batch 256, a training-only scaler excluding all day-7 cells, and common source/target identities capped at 1,200 per donor. ED is energy distance in the common standardized encoder coordinates. Means equally weight donors and seeds. The seed range covers three equal-donor means, not a biological confidence interval. The centroid comparator uses the same donor\textquotesingle s day-1/day-30 means with the relevant time fraction. The final column is the maximum absolute donor/seed ED change from 50 to 200 RK4 steps, not proof of solver convergence. CPU checkpoint reload reproduces the predictions; no clock is selected using the held target.',['Clock','Flow ED','Flow seed range','Centroid ED','Unchanged ED','Max refinement change'],rows,[25,23,42,26,26,23]))
d=report('donor_conditioned_benchmark')
names={'M0_standstill':'Stay-still','M1_shared_cfm':'Shared CFM','M2_mean_displacement':'Mean displacement','M3_nearest_donor':'Nearest donor','M4_conditioned_cfm':'Conditioned CFM','M5_optimal_transport':'Entropic OT extension'}
rows=[[names[m],f(v['mean_ed']),f(v['mean_gain']),f"{v['n_pass']}/{v['n']}"] for m,v in d['summary'].items()]
p2.append(table('tab:p2methods','Common Wound1-to-Wound7 benchmark across the three held-out human donors. ED is empirical energy distance in each training-standardized fold; reported means equally weight donors. Gain is stay-still ED minus method ED. Pass count records gains above the single split-half target reference, a descriptive criterion rather than a significance test. CFM denotes conditional flow matching and OT the entropic optimal-transport displacement extension. All methods share test donors; point estimates without confidence intervals do not establish a population ranking.',['Method','Mean ED','Mean gain','Pass count'],rows,[68,34,34,31]))
rows=[]
for m,vs in d['per_donor'].items():rows.append([names[m],*[f(vs[n]['ed']) for n in ['PWH26','PWH27','PWH28']]])
p2.append(table('tab:p2methodsbydonor','Empirical energy distances for each method and held-out human donor in the common benchmark. Each column uses the other two donors for fitting and scaling, the named donor\'s Wound1 cells as source and its Wound7 cells only for evaluation. Lower is better; stay-still retains the source distribution. CFM means conditional flow matching; OT is the entropic transport displacement extension. Entries are point estimates with a 1,200-cell distance cap. Training draws and this cap differ from separately run transfer experiments, so those point estimates need not coincide.',['Method','PWH26','PWH27','PWH28'],rows,[68,34,34,31]))
curve=json.loads((REVISION/'population/report.json').read_text())['curve']
cfm=next(r for r in curve['summary'] if r['method']=='Shared CFM')
rows=[[r['held_donor'],f(r['k1_ed']),f(r['k2_ed']),f(r['reduction'])] for r in curve['donor_blocks'] if r['method']=='Shared CFM']
p2.append(table('tab:p2curve',r'Seed-averaged donor-count comparison after returning each prediction to the frozen encoder space and scoring in a common reference within held donor. The reference uses both non-held donors and never enters a single-donor fit. ED is empirical energy distance; k is the number of training donors. Single-donor choices are averaged within held donor and seed, followed by seeds 0, 1 and 2. Reduction is k=1 minus k=2. The donor-balanced reduction is '+f(cfm['mean_reduction'])+r', with a descriptive three-block percentile 95\% range ['+f(cfm['descriptive_block_range_lower'])+', '+f(cfm['descriptive_block_range_upper'])+r']. Overlapping training sets prevent interpreting this range as a population coverage guarantee.',['Held donor','k=1 ED','k=2 ED','Reduction'],rows,[53,38,38,38]))
d=report('mouse_all_arms_pod7_audit')
rows=[[n,f(v['energy_distance_standstill']),f(v['energy_distance_predicted']),f(100*v['improvement_fraction'],2)+'%', 'Yes' if v['holdout_on_direct_path'] else 'No'] for n,v in d['arms'].items()]
p2.append(table('tab:p2mouse','Mouse POD7 audit for the source-labelled NDB, PDB and GDB arms. Each field uses rank time and POD0, POD2 and POD30 for fitting/scaling, then predicts from POD2 to excluded POD7. ED is empirical energy distance; improvement is 100 times (stay-still ED minus predicted ED) divided by stay-still ED. Each arm covers 4,182/7,002 human-panel genes and has one animal per time point. The ordering check asks whether endpoint distance is at least both endpoint-to-target distances; it is not proof of a geodesic. Values have no confidence intervals, and cell counts do not provide animal replication.',['Arm','Stay-still ED','Predicted ED','Improvement','Ordering check'],rows,[22,36,36,34,37]))
rows=csvrows('donor_geometry_inference.csv')
p2.append(table('tab:p2geometrytable',r'Descriptive geometry for three healthy acute-wound donors. The first estimate divides the median of 18 within-donor between-time energy distances by the median of 12 between-donor same-time distances. The second is the mean of three pairwise cosines between donor Wound1-to-Wound7 mean-displacement vectors. Endpoints are percentile 95\% limits from 10,000 resamples of pairwise distances within class or of cosine pairs. Pairs share donors, so these intervals do not provide independent donor replication or a general population ordering.',['Summary','Estimate','Lower endpoint','Upper endpoint'],[[r['metric'].replace('_',' '),f(r['estimate']),f(r['ci_low']),f(r['ci_high'])] for r in rows],[72,30,33,32]))

d=report('donor_conditioned_benchmark')
rows=[[key.split('/')[0],key.split('/')[1],f(v['standstill']),f(v['shared']),f(v['conditioned'])] for key,v in d['in_sample'].items()]
p2.append(table('tab:p2insample',r'All six training-donor comparisons for shared and donor-conditioned flow matching. The first column identifies the donor excluded from that fit; the second is a retained training donor whose Wound1-to-Wound7 prediction is evaluated. ED is empirical energy distance in the fold-standardized coordinates. Both source and target of the evaluated donor were available during fitting, so these are fitting-capacity comparisons rather than donor-transfer tests. Conditioned errors are lower in all six rows. The repeated use of three donors prevents interpreting the rows as six independent biological replicates.',['Excluded donor','Evaluated training donor','Stay-still ED','Shared ED','Conditioned ED'],rows,[32,47,29,27,30]))
rows=[]
short_methods={'Shared CFM':'Shared CFM','Mean displacement':'Mean displacement','Training-target marginal (exact)':'Target marginal, full','Training-target marginal (matched)':'Target marginal, matched','Unchanged source':'Unchanged source'}
for v in curve['by_seed']:
 if v['method']=='Shared CFM' or int(v['seed'])==0:
  rows.append([short_methods[v['method']],str(v['seed']) if v['method']=='Shared CFM' else 'Fixed',f(v['k1_ed']),f(v['k2_ed']),f(v['reduction'])])
p2.append(table('tab:p2seedcurve',r'Donor-count means in common reference coordinates. CFM denotes conditional flow matching; ED is empirical energy distance. The three CFM seeds reset both endpoint and network random generators. Deterministic controls are listed once. Full target-marginal prediction assigns equal mass to each selected training donor; matched prediction averages 50 draws with the same particle count as the held-source distribution. k=1 averages the two available single-training-donor choices before equally weighting held donors. Evaluation targets and scoring coordinates remain fixed across k and seed. Positive reductions favour k=2; these computational configurations retain three biological donors.',['Predictor','Seed','k=1 mean ED','k=2 mean ED','Reduction'],rows,[49,17,35,35,29]))
stability=list(csv.DictReader((REVISION/'population/configuration_stability.csv').open()))
rows=[[v['held_donor'],v['training_donors'],v['k'],f(v['mean_ed']),f(v['training_sd']),f(v['training_range'])] for v in stability if v['method']=='Shared CFM']
p2.append(table('tab:p2seedconfigs',r'Training stochasticity in common reference coordinates for every shared-field donor/training-subset configuration. Mean ED, sample SD and range summarize seeds 0, 1 and 2; range is maximum minus minimum. The observed source and target indices, target split and reference scaler are fixed within held donor, so variation within each row reflects fitting randomness. Seeds and overlapping training subsets are not independent donors. The single split-half target reference measures finite-cell sampling and omits fitting variation.',['Held donor','Training donors','k','Mean ED','SD','Range'],rows,[28,53,12,26,23,23]))
d=report('mouse_all_arms_pod7_audit');rows=[]
for name,v in d['arms'].items():rows.append([name,*[v['n_cells_by_pod'][t] for t in ['POD0','POD2','POD7','POD30']],f(v['energy_distance_noise_floor'],5)])
p2.append(table('tab:p2mousecounts',r'Fibroblast cell counts and target-sampling reference for each mouse arm. POD means postoperative day. POD0, POD2 and POD30 enter training; POD7 is the held-out target. Every arm/timepoint cell group comes from one animal, so these counts quantify distribution sampling and not biological replication. The final column is one seeded split-half POD7 energy distance in the training-standardized space. NDB, PDB and GDB are retained source-study arm labels. All arms share 4,182/7,002 mapped panel genes.',['Arm','POD0','POD2','POD7 held out','POD30','Split-half ED'],rows,[21,27,27,34,27,29]))

# Place mouse cell counts beside the mouse errors; end with all seed configurations.
p2.insert(6, p2.pop())

r=json.loads((ROOT/'outputs/robustness_extensions/report.json').read_text())['temporal']
rows=[[v['rk4_steps'],f(v['energy_distance'],9),f(100*v['relative_improvement'],6)+'%',f"{v['rms_coordinate_difference_from_200']:.3g}"] for v in r['numerical_sensitivity']['rows']]
p2.append(table('tab:p2numerics',r'Fixed-field Runge--Kutta resolution comparison for pooled day-7 holdout. A single seed-0 field was refitted with the specified 8,000 optimization steps and 256-cell batches on the saved expression coordinates, excluding day 7 from fitting and scaling. All rows use the same 1,012 day-1 cells and the same 1,500 sampled target cells. Energy distance is the empirical V-statistic evaluated in double precision; improvement is relative to the same unchanged-source baseline (1.406924). RMS is the root-mean-square coordinate difference from the 200-step solution; it is a numerical discrepancy, not a confidence interval. The comparison is conditional on one field and finite-precision arithmetic and does not establish formal convergence to an exact ODE solution.',['RK4 steps','Energy distance','Improvement','RMS vs 200 steps'],rows,[28,46,44,48]))
rows=[[v['cells_per_distribution'],v['draws'],f(100*v['median_relative_improvement'],2)+'%',f(100*v['central_95_draw_range'][0],2)+' to '+f(100*v['central_95_draw_range'][1],2)+'%',str(v['gain_exceeds_split_half_count'])+'/'+str(v['draws'])] for v in r['evaluation_sampling']['summary']]
p2.append(table('tab:p2sampling',r'Evaluation-sampling sensitivity for the same fixed field with 50 RK4 steps. For each cell count, 50 seeded draws sample source and target cells without replacement; prediction and unchanged-source comparisons use identical source indices and identical target indices within a draw. An additional pair of disjoint target subsets at that count defines a split-half reference. Percentages summarize relative improvement over unchanged source; the central 95\% draw range measures Monte Carlo sensitivity conditional on this cohort and field, not patient-level confidence. The final column counts draws whose gain exceeds the split-half reference. Cell count and resampling do not increase the three-donor biological sample size.',['Cells per distribution','Draws','Median improvement','Central 95% draw range','Gain exceeds reference'],rows,[34,17,37,42,37]))
d=json.loads((ROOT/'outputs/mathematical_audit/population/report.json').read_text())
rows=[[v['evaluation'],f"{v['n_source']} / {v['n_target']}",f(v['stay_still_distance'],5),f(v['predicted_distance'],5),f(100*v['relative_improvement'],2)+'%'] for v in d['evaluation']]
p2.append(table('tab:p2weights',r'Evaluation of the saved pooled 50-step field in training-standardized coordinates, using all 1,012 Wound1 and 3,821 Wound7 cells. ED is the double-precision weighted empirical energy distance, without subsampling. Cell-pooled weights are uniform; donor-balanced weights allocate one third to each donor and equal mass within donor. Predictions retain source weights. The final three rows evaluate training donors separately, not donor-transfer folds. Improvement uses the corresponding unchanged-source ED. These three-donor point estimates have no confidence intervals and differ from capped-distance estimates.',['Evaluation','Source / target cells','Stay-still ED','Predicted ED','Improvement'],rows,[40,37,31,31,28]))
bio=ROOT/'outputs/biological_expansion/population'
rows=list(csv.DictReader((bio/'donor_time_counts.csv').open()))
donors={'PWH26':'Donor A','PWH27':'Donor B','PWH28':'Donor C'}
counts={(r['donor'],r['cond']):r['cells'] for r in rows}
p2.append(table('tab:p2biologicalcounts',r'Observed author-annotated fibroblasts retained after the sample--barcode join in GSE241132. Donors A, B and C correspond to source donor labels PWH26, PWH27 and PWH28. Each cell-count entry comes from one biopsy; the three donors supply the biological replication. The 12 entries sum to 12,259 cells and provide the material for expression and geometry displays. Day 0 is intact skin, followed by acute wounds at days 1, 7 and 30.',['Donor','Day 0 cells','Day 1 cells','Day 7 cells','Day 30 cells'],[[donors[d],*[counts[(d,c)] for c in ['Skin','Wound1','Wound7','Wound30']]] for d in donors],[33,33,33,33,33]))
rows=list(csv.DictReader((bio/'baseline_summary.csv').open()))
p2.append(table('tab:p2interpolation',r'Retrospective global missing-time comparison in three donors. Each error is the equally weighted mean of three within-donor, full-cell empirical energy distances in all 15 training-standardized coordinates. The table gives its mean and range over seeds 0, 1 and 2; deterministic baselines have zero seed range. Improvement is relative to the corresponding unchanged-source error. Withheld day 7 uses day 1 as source and day 30 as anchor; withheld day 1 uses intact skin as source and day 7 as anchor. Both have rank-time interpolation fraction one half. The held-time cells are excluded from scaling, fitting and anchor construction. Seed ranges are not donor confidence intervals, and absolute errors from different tasks use different scalers.',['Held day','Predictor','Mean ED','Minimum ED','Maximum ED','Mean improvement'],[[r['holdout'].replace('Wound',''),r['method'],f(r['energy_mean']),f(r['energy_min']),f(r['energy_max']),f(100*float(r['improvement_mean']),2)+'%'] for r in rows],[17,42,24,24,24,32]))
raw=list(csv.DictReader((bio/'baseline_by_donor_seed.csv').open()))
rows=[]
for h in ['Wound7','Wound1']:
 for d in donors:
  for m in ['Unchanged source','Centroid translation','Independent bridge','Shared flow']:
   values=[float(r['energy_distance']) for r in raw if r['holdout']==h and r['donor']==d and r['method']==m]
   rows.append([h.replace('Wound',''),donors[d],m,f(sum(values)/len(values)),f(min(values)),f(max(values))])
p2.append(table('tab:p2interpolationdonors',r'Every donor-specific error in the two global missing-time tasks, summarized over the three computational seeds. ED is the full 15-dimensional empirical energy distance using all available source-derived predictions and target cells in that donor. The mean, minimum and maximum describe seeds, not independent specimens. The centroid baseline has lower seed-averaged error than the field in all three day-7 donors and two of three day-1 donors. Each donor supplies both training endpoints in this retrospective design; these rows are not held-out-donor transfer.',['Held day','Donor','Predictor','Mean ED','Minimum ED','Maximum ED'],rows,[17,24,48,24,24,24]))
extra=ROOT/'outputs/computational_extension/population'
rows=list(csv.DictReader((extra/'geometry_summary.csv').open()))
p2.append(table('tab:p2shapediagnostics',r'Geometry controls for globally withheld days 7 and 1. Entries average seeds within each donor and then weight the three donors equally. ED is full-cell empirical energy distance in the 15 training-standardized coordinates. Centered ED subtracts each distribution\textquotesingle s own mean only for evaluation; it is a separate shape diagnostic and is not an additive error decomposition. Centroid error is Euclidean distance between means. Variance ratio is predicted total coordinate variance divided by observed target variance. Location--scale interpolates only the permitted endpoint means and standard deviations at rank fraction one half; no target mean or dispersion enters prediction. All entries are point estimates, not population uncertainty intervals.',['Held day','Predictor','ED','Centered ED','Centroid error','Variance ratio'],[[r['holdout'].replace('Wound',''),r['method'],f(r['energy_distance']),f(r['centered_energy']),f(r['centroid_error']),f(r['variance_ratio'],3)] for r in rows],[17,41,25,28,28,25]))
rows=list(csv.DictReader((extra/'matched_cell_summary.csv').open()))
p2.append(table('tab:p2matchedsampling',r'Matched evaluation with 200 source and 200 target cells per donor, sampled without replacement in 50 draws with seed 29. Each draw shares indices across all predictors and fit seeds, then averages seeds within donor and donors equally. Entries are shared-flow error minus comparator error; positive differences favor the comparator. Full ranges describe observed-cell resampling sensitivity, not donor confidence intervals or hypothesis tests. The 50 draws still involve only the same three biological donors.',['Held day','Comparator','Mean difference','Full draw range','Comparator lower'],[[r['holdout'].replace('Wound',''),r['comparator'],f(r['flow_minus_comparator_mean']),f(r['difference_min'])+' to '+f(r['difference_max']),r['comparator_lower_count']+'/'+r['draws']] for r in rows],[19,45,32,41,27]))
marginal=json.loads((REVISION/'population/historical_benchmark/report.json').read_text())
rows=[[v['held_donor'],f(v['shared_cfm_ed']),f(v['matched_equal_donor_mean_ed']),f(v['matched_equal_donor_min_ed'])+' to '+f(v['matched_equal_donor_max_ed']),str(v['marginal_lower_draws'])+'/'+str(v['draws'])] for v in marginal['donor_summary']]
p2.append(table('tab:p2targetmarginal',r'Training-target marginal predictor compared with the historical shared-field benchmark. Each target-marginal draw samples the permitted training donors\textquotesingle{} Wound7 cells without replacement, matches the original held-source particle count (255, 497 or 260), and assigns each training donor exactly half of total probability mass. It uses no held-source expression. Scaling and target indices are identical to the original benchmark. Means and full ranges describe 50 draws; they are not donor confidence intervals. The shared-field column is its original saved error, because historical per-cell predictions were unavailable for a new paired evaluation. Across donors the matched marginal mean is '+f(marginal['matched_equal_donor']['mean'])+' versus '+f(marginal['original_shared_cfm_mean_ed'])+r' for the field; lower is better.',['Held donor','Shared-field ED','Target-marginal ED','Full draw range','Marginal lower'],rows,[27,30,35,46,27]))
ablation=json.loads((REVISION/'source_ablation/report.json').read_text())
rows=[[r['held_donor'],f(r['real_ed']),f(r['wrong_ed']),f(r['marginal_ed']),f(r['wrong_minus_real'])] for r in ablation['per_donor']]
mean=ablation['macro_equal_donor']
rows.append(['Three-donor mean',f(mean['real_ed']),f(mean['wrong_ed']),f(mean['marginal_ed']),f(mean['wrong_minus_real'])])
p2.append(table('tab:p2sourceswap',r'Retrospective source-replacement control for the nine saved two-training-donor fields (three held donors by three seeds). All scores are empirical energy distance in the same reference coordinates and on the same held-donor Wound7 target cells; lower is better. Real is the actual held-donor Wound1 distribution. Substituted sources are 50 without-replacement, source-count-matched draws from permitted training donors\textquotesingle{} Wound1 cells, integrated by the identical saved field, with one-half mass assigned to each training donor. The target marginal instead draws from their Wound7 cells without reading the held source; its draw IDs are not paired with substituted-source draws. Draws are averaged within field, then seeds within held donor; the final row equally weights three donors. The difference is substituted minus real, so a negative value favors the substituted input. These are retrospective, dependent computations on three healthy donors, not confidence intervals, new biological replicates or a model-selection test.',['Held donor','Real-source ED','Substituted ED','Target marginal ED','Substituted minus real'],rows,[31,27,29,33,35]))
mixture=json.loads((LATEST/'population_mixture/report.json').read_text())
rows=[[v['held_donor'],f(v['individual_mean_ed'],6),f(v['mixed_ed'],6),f(v['convexity_gain'],6),f(v['quarter_component_pair_ed'],6)] for v in mixture['exact_marginal']['per_fold']]
v=mixture['exact_marginal']['macro']
rows.append(['Three-donor mean',f(v['individual_mean_ed'],6),f(v['mixed_ed'],6),f(v['convexity_gain'],6),f(v['quarter_component_pair_ed'],6)])
p2.append(table('tab:p2mixtureidentity',r'Exact target-marginal mixture decomposition in fixed held-fold coordinates. Separate ED is the mean of the two single-training-donor target errors; mixed ED scores their equal-mass empirical mixture. Reduction is separate minus mixed and equals one quarter of their mutual ED, independently of the held target. ED denotes the empirical energy discrepancy without its square root. Complete permitted training-Wound7 distributions and the original held-target indices reproduce the earlier full-marginal curve. Maximum identity residual is '+f(v['maximum_absolute_identity_residual'],16)+r'. The final row equally weights three donors. This identity does not decompose a jointly fitted neural field, and lower mixture error does not itself identify target-relevant information gain.',['Held donor','Separate ED','Mixed ED','Reduction','Mutual ED / 4'],rows,[35,33,33,33,33]))
rows=[[v['held_donor'],f(v['real_ed']),v['wrong_a_donor']+': '+f(v['wrong_a_ed']),v['wrong_b_donor']+': '+f(v['wrong_b_ed']),f(v['mixed_wrong_ed'])] for v in mixture['source_comparison']['per_donor']]
v=mixture['source_comparison']['macro']
rows.append(['Three-donor mean',f(v['real_ed']),f(v['wrong_a_ed']),f(v['wrong_b_ed']),f(v['mixed_wrong_ed'])])
p2.append(table('tab:p2mixtureaudit',r'Matched-particle source substitutions in nine existing two-training-donor fields (three held donors, seeds 0--2). Each score uses 200 predicted particles: real held-source cells, one individual permitted training-donor source, or a mixture of 100 cells from each permitted donor. Fifty without-replacement draws share fixed held-target indices and reuse source indices across model seeds. Wrong A/B list actual source donors; their identities vary across held folds, so the final columns average fold-specific substitutions, not a single common donor. Scores average draws within field, then seeds within held donor, then donors equally. The individual-substitution error average is '+f(v['individual_wrong_mean_ed'])+r'. These are point energy discrepancies in common reference coordinates, not confidence intervals or new biological replication. Mixture identities are separately checked on the actual 100-cell components, not by equating them to the 200-cell individual distributions. No model is refitted.',['Held donor','Real-source ED','Wrong A ED','Wrong B ED','Mixed ED'],rows,[34,30,37,37,29]))
observable=json.loads((AUDIT/'population_observable/final-01/report.json').read_text())
observable_names={'shared_cfm_decoded':'Decoded shared flow','persistence_decoded':'Decoded persistence','mean_displacement_decoded':'Decoded mean displacement','training_target_marginal_decoded_exact':'Decoded training marginal','persistence_observed':'Observed persistence','training_target_marginal_observed_exact':'Observed training marginal'}
rows=[]
for target in ('original_evaluation','all_day7'):
 for k in (1,2):
  for method,label in observable_names.items():
   v=next(x for x in observable['macro'] if x['target_set']==target and x['k']==k and x['method']==method)
   rows.append(['Saved target' if target=='original_evaluation' else 'All day 7',str(k),label,f(v['total_variation']),f(v['js_divergence_nats']),f(v['gene_rmse'],6)])
p2.append(table('tab:p2observable',r'Observable-space errors against actual held-donor expression in the same three healthy volunteers. All 5,383 assayed frozen-panel genes are retained without a performance filter; 1,619 absent genes are not observed zeros. Each observed cell or decoded particle is normalized on the common panel before equal-cell averaging. Saved target uses the original held-target identities; all day 7 is a predeclared sensitivity. k counts permitted training donors, not test donors. Twenty-seven saved fits use three computational seeds; no model is trained. Averages weight seeds, then training subsets, then held donors equally. TV is total variation between mean profiles; JS is Jensen--Shannon divergence in natural-log units, not its square root; RMSE is the root mean square error over gene proportions. Lower is better. Observed and decoded baselines are distinct; training marginals use only permitted donors. These are mean-profile errors, not single-cell transitions, full distributional fidelity, absolute-count prediction or biological confidence intervals.',['Target set','k','Predictor','TV','JS (nats)','Gene RMSE'],rows,[26,9,53,24,25,28]))
rows=[]
for v in observable['decoder_reference']:
 rows.append([v['held_donor'],'Saved target' if v['target_set']=='original_evaluation' else 'All day 7',str(v['n_target']),f(v['total_variation']),f(v['js_divergence_nats']),f(100*v['missing_panel_mass_mean'],2)+'%'])
p2.append(table('tab:p2decoderreference',r'Decoder reconstruction reference for the observed held-donor day-7 cells. The frozen encoder means of the target cells themselves are decoded, restricted to the same 5,383 observed panel genes and normalized per cell before averaging. Errors compare this reconstruction with actual mean observed expression, not with another decoded target. TV is total variation; JS is Jensen--Shannon divergence in nats. The missing-mass column reports mean decoder probability on the 1,619 unmeasured panel genes before renormalization. This reference uses held-target information: it is not a forecast, true expression, a competing predictor or a mathematical lower error bound. The two target sets overlap and do not add independent observations.',['Held donor','Target set','Cells','TV','JS (nats)','Unmeasured mass'],rows,[26,32,22,25,27,33]))
(HERE/'tables.tex').write_text('\n\n'.join(p2)+'\n')
print('Exported supplementary numerical tables from reports without fitting models.')
