#!/usr/bin/env python3
"""Export numerical supplementary tables from completed reports; no model fitting."""
from pathlib import Path
import csv,json
ROOT=Path(__file__).resolve().parents[2]
HERE=Path(__file__).resolve().parent
ANALYSIS=ROOT/'outputs/analysis'
TOPIC_LABELS=['TIMP1/COL3A1', 'JUNB/DNAJB1', 'COL1A1/COL1A2', 'IGFBP7/IGFBP5', 'TAGLN/ACTA2', 'KRT14/KRT10', 'CFD/APOD', 'DCN/CFD', 'DCD/SAT1', 'IGFBP7/SPARCL1', 'FOS/IGFBP7', 'HLA-DRA/CD74', 'IGFBP7/TAGLN', 'FOS/JUNB', 'DNAJB1/FOS']
def report(n):return json.loads((ANALYSIS/n/'report.json').read_text())
def esc(x):
 return str(x).replace('&',r'\&').replace('%',r'\%').replace('_',r'\_').replace('#',r'\#')
def historical(n):return json.loads((ROOT/'outputs'/n/'report.json').read_text())
def probability(x):return f'{float(x):.3g}' if x is not None else '—'
def f(x,n=4):return '—' if x in (None,'') else f'{float(x):.{n}f}'
def table(label,caption,headers,rows,widths):
 col='@{}'+''.join('p{'+str(w)+'mm}' for w in widths)+'@{}'
 header=' & '.join(r'\textbf{'+esc(h)+'}' for h in headers)+r' \\'
 # Longtable measures its caption/header and starts only when a row fits.
 # Keep the first and last row pairs together without reserving an estimated
 # table height, which can push otherwise usable content onto another page.
 body='\n'.join(' & '.join(esc(c) for c in row)+(r' \\*' if len(rows)>1 and i in (0,len(rows)-2) else r' \\') for i,row in enumerate(rows))
 return '\n'.join([r'{\small',r'\begin{longtable}{'+col+'}',r'\caption{'+caption+r'}\label{'+label+r'}\\',r'\toprule',header,r'\midrule\endfirsthead',r'\multicolumn{'+str(len(headers))+r'}{l}{\tablename\ \thetable\ (continued)}\\',r'\toprule',header,r'\midrule\endhead',r'\bottomrule\endfoot',body,r'\end{longtable}',r'}'])
def csvrows(n):return list(csv.DictReader((ROOT/'manuscripts/tables'/n).open()))
# Each exported table lives in TeX; no Markdown draft is used by the build.
p2=[]
h=report('human_temporal_flow');d=report('donor_transfer_flow')
rows=[['Pooled time holdout',f(h['all_donors']['standstill']),f(h['all_donors']['predicted']),f(h['all_donors']['noise_floor']),f(h['all_donors']['improvement']*100,2)+'%']]
for name,v in h['leave_one_donor_out'].items():rows.append(['Drop '+name+'; retained pair',f(v['standstill']),f(v['predicted']),f(v['noise_floor']),f(v['improvement']*100,2)+'%'])
for name,v in d['per_donor'].items():rows.append([name+' transfer',f(v['ed_standstill']),f(v['ed_predicted']),f(v['noise_floor']),f(v['improvement']*100,2)+'%'])
p2.append(table('tab:p2folds','Human Wound7 evaluation in GSE241132. ED denotes the empirical energy-distance V-statistic in training-standardized latent space; lower values indicate closer predicted and observed distributions. The pooled row excludes Wound7 globally. Drop-one rows exclude the named donor and evaluate pooled Wound7 only in the two retained donors. Transfer rows instead evaluate the excluded donor after fitting all four time points of the other donors. Improvement is 100 times (stay-still ED minus predicted ED) divided by stay-still ED. Split-half ED uses one seeded target split and is not a confidence limit. Every row is a point estimate; these dependent fits do not create additional donors.',['Evaluation','Stay-still ED','Predicted ED','Split-half ED','Improvement'],rows,[50,28,28,28,31]))
d=report('time_parameterisation')
rows=[[n.replace('_',' '),f(v['t_holdout']),f(v['ed_at_claimed']),f(v['improvement_at_claimed']*100,2)+'%',str(v['diverged'])] for n,v in d['axes_results'].items()]
p2.append(table('tab:p2axes','Four time coordinates under global Wound7 holdout. The reference distance is '+f(d['standstill'])+' and the split-half distance is '+f(d['noise_floor'])+'. ED denotes empirical energy distance in training-standardized latent space. Wound7 time is the global transformed coordinate; the reported target distance is evaluated at the nearest point of the 60-step Wound1-to-Wound30 scan. Improvement is 100 times the gain divided by stay-still distance. Rows use the same three donors, with Wound7 excluded globally; the path minimum is not substituted for target error, and no interval is shown.',['Time coordinate','Wound7 time','Target ED','Improvement','Diverged'],rows,[41,32,31,32,29]))
d=report('donor_conditioned_benchmark')
names={'M0_standstill':'Stay-still','M1_shared_cfm':'Shared CFM','M2_mean_displacement':'Mean displacement','M3_nearest_donor':'Nearest donor','M4_conditioned_cfm':'Conditioned CFM','M5_optimal_transport':'Entropic OT extension'}
rows=[[names[m],f(v['mean_ed']),f(v['mean_gain']),f"{v['n_pass']}/{v['n']}"] for m,v in d['summary'].items()]
p2.append(table('tab:p2methods','Common Wound1-to-Wound7 benchmark across the three held-out human donors. ED is empirical energy distance in each training-standardized fold; reported means equally weight donors. Gain is stay-still ED minus method ED. Pass count records gains above the single split-half target reference, a descriptive criterion rather than a significance test. CFM denotes conditional flow matching and OT the entropic optimal-transport displacement extension. All methods share test donors; point estimates without confidence intervals do not establish a population ranking.',['Method','Mean ED','Mean gain','Pass count'],rows,[68,34,34,31]))
rows=[]
for m,vs in d['per_donor'].items():rows.append([names[m],*[f(vs[n]['ed']) for n in ['PWH26','PWH27','PWH28']]])
p2.append(table('tab:p2methodsbydonor','Empirical energy distances for each method and held-out human donor in the common benchmark. Each column uses the other two donors for fitting and scaling, the named donor\'s Wound1 cells as source and its Wound7 cells only for evaluation. Lower is better; stay-still retains the source distribution. CFM means conditional flow matching; OT is the entropic transport displacement extension. Entries are point estimates with a 1,200-cell distance cap. Training draws and this cap differ from separately run transfer experiments, so those point estimates need not coincide.',['Method','PWH26','PWH27','PWH28'],rows,[68,34,34,31]))
d=report('donor_curve_inference')
rows=[[r['held_out_donor'],f(r['k1_mean_ed']),f(r['k2_mean_ed']),f(r['mean_reduction'])] for r in d['held_out_donor_summary']]
p2.append(table('tab:p2curve',r'Seed-averaged donor-count comparison for shared flow matching. ED is empirical energy distance and k is the number of training donors. At k=1, the two single-training-donor choices are averaged within each held donor and seed; each row then averages seeds 0, 1 and 2. Reduction is k=1 ED minus k=2 ED. The equally weighted mean reduction is 0.1655, with a 4,000-draw percentile 95\% interval [0.0813, 0.3146] from three held-donor blocks. Training sets overlap; this descriptive interval is not a population coverage guarantee or evidence of a learning-curve plateau.',['Held donor','k=1 ED','k=2 ED','Reduction'],rows,[53,38,38,38]))
d=report('mouse_all_arms_pod7_audit')
rows=[[n,f(v['energy_distance_standstill']),f(v['energy_distance_predicted']),f(100*v['improvement_fraction'],2)+'%', 'Yes' if v['holdout_on_direct_path'] else 'No'] for n,v in d['arms'].items()]
p2.append(table('tab:p2mouse','Mouse POD7 audit for the source-labelled NDB, PDB and GDB arms. Each field uses rank time and POD0, POD2 and POD30 for fitting/scaling, then predicts from POD2 to excluded POD7. ED is empirical energy distance; improvement is 100 times (stay-still ED minus predicted ED) divided by stay-still ED. Each arm covers 4,182/7,002 human-panel genes and has one animal per time point. The ordering check asks whether endpoint distance is at least both endpoint-to-target distances; it is not proof of a geodesic. Values have no confidence intervals, and cell counts do not provide animal replication.',['Arm','Stay-still ED','Predicted ED','Improvement','Ordering check'],rows,[22,36,36,34,37]))
rows=csvrows('donor_geometry_inference.csv')
p2.append(table('tab:p2geometrytable',r'Descriptive geometry for three healthy acute-wound donors. The first estimate divides the median of 18 within-donor between-time energy distances by the median of 12 between-donor same-time distances. The second is the mean of three pairwise cosines between donor Wound1-to-Wound7 mean-displacement vectors. Endpoints are percentile 95\% limits from 10,000 resamples of pairwise distances within class or of cosine pairs. Pairs share donors, so these intervals do not provide independent donor replication or a general population ordering.',['Summary','Estimate','Lower endpoint','Upper endpoint'],[[r['metric'].replace('_',' '),f(r['estimate']),f(r['ci_low']),f(r['ci_high'])] for r in rows],[72,30,33,32]))

d=report('donor_conditioned_benchmark')
rows=[[key.split('/')[0],key.split('/')[1],f(v['standstill']),f(v['shared']),f(v['conditioned'])] for key,v in d['in_sample'].items()]
p2.append(table('tab:p2insample',r'All six training-donor comparisons for shared and donor-conditioned flow matching. The first column identifies the donor excluded from that fit; the second is a retained training donor whose Wound1-to-Wound7 prediction is evaluated. ED is empirical energy distance in the fold-standardized coordinates. Both source and target of the evaluated donor were available during fitting, so these are fitting-capacity comparisons rather than donor-transfer tests. Conditioned errors are lower in all six rows. The repeated use of three donors prevents interpreting the rows as six independent biological replicates.',['Excluded donor','Evaluated training donor','Stay-still ED','Shared ED','Conditioned ED'],rows,[32,47,29,27,30]))
d=report('donor_curve_seed_stability');c=report('donor_count_curve');rows=[]
for seed,v in d['per_seed'].items():rows.append(['Shared CFM',seed,f(v['k1_mean_ed']),f(v['k2_mean_ed']),f(v['reduction_k1_to_k2'])])
rows.append(['Mean displacement','0',f(c['curve']['k_1']['mean_displacement_mean_ed']),f(c['curve']['k_2']['mean_displacement_mean_ed']),f(c['step_one_to_two_donors']['mean_displacement_ed_reduction_k1_to_k2'])])
p2.append(table('tab:p2seedcurve',r'Donor-count means by training seed and non-neural control. CFM denotes conditional flow matching, ED empirical energy distance and k the number of training donors. At k=1, two available single-donor fits are averaged within held donor; at k=2 one fit uses both available donors. Means then equally weight the three held donors. Reduction is k=1 minus k=2. CFM evaluation subsamples are fixed across seeds 0, 1 and 2; the mean-displacement control is recorded at seed 0. All nine CFM runs per seed and all six/three control runs at k=1/k=2 meet the descriptive split-half criterion. The control also improves with a second donor.',['Predictor','Seed','k=1 mean ED','k=2 mean ED','Reduction'],rows,[49,17,35,35,29]))
rows=[[v['held_out_donor'],', '.join(v['training_donors']),v['k'],f(v['mean']),f(v['sd']),f(v['range'])] for v in d['training_stochasticity']['per_cell']]
p2.append(table('tab:p2seedconfigs',r'Training stochasticity for every held-donor/training-subset configuration. Mean ED, sample SD and range summarize the same fit repeated at seeds 0, 1 and 2; range is maximum minus minimum. Evaluation subsampling and the target split are fixed, so variation reflects training randomness. Averaging the nine configuration SDs gives 0.0717, 3.13 times the mean split-half reference 0.0229; the maximum range is 0.3683. Seeds and overlapping subsets are not independent donors and the single split-half criterion omits this training variability.',['Held donor','Training donors','k','Mean ED','SD','Range'],rows,[28,53,12,26,23,23]))
d=report('mouse_all_arms_pod7_audit');rows=[]
for name,v in d['arms'].items():rows.append([name,*[v['n_cells_by_pod'][t] for t in ['POD0','POD2','POD7','POD30']],f(v['energy_distance_noise_floor'],5)])
p2.append(table('tab:p2mousecounts',r'Fibroblast cell counts and target-sampling reference for each mouse arm. POD means postoperative day. POD0, POD2 and POD30 enter training; POD7 is the held-out target. Every arm/timepoint cell group comes from one animal, so these counts quantify distribution sampling and not biological replication. The final column is one seeded split-half POD7 energy distance in the training-standardized space. NDB, PDB and GDB are retained source-study arm labels. All arms share 4,182/7,002 mapped panel genes.',['Arm','POD0','POD2','POD7 held out','POD30','Split-half ED'],rows,[21,27,27,34,27,29]))

# Place mouse cell counts beside the mouse errors; end with all seed configurations.
p2.insert(6, p2.pop())

r=json.loads((ROOT/'outputs/robustness_extensions/report.json').read_text())['temporal']
rows=[[v['rk4_steps'],f(v['energy_distance'],9),f(100*v['relative_improvement'],6)+'%',f"{v['rms_coordinate_difference_from_200']:.3g}"] for v in r['numerical_sensitivity']['rows']]
p2.append(table('tab:p2numerics',r'Fixed-field Runge--Kutta resolution comparison for pooled day-7 holdout. A single seed-0 field was refitted with the specified 8,000 optimization steps and 256-cell batches on the saved expression coordinates, excluding day 7 from fitting and scaling. All rows use the same 1,012 day-1 cells and the same 1,500 sampled target cells. Energy distance is the empirical V-statistic evaluated in double precision; improvement is relative to the same unchanged-source baseline (1.406924). RMS is the root-mean-square coordinate difference from the 200-step solution; it is a numerical discrepancy, not a confidence interval. The comparison is conditional on one field and finite-precision arithmetic and does not establish formal convergence to an exact ODE solution.',['RK4 steps','Energy distance','Improvement','RMS vs 200 steps'],rows,[28,46,44,48]))
rows=[[v['cells_per_distribution'],v['draws'],f(100*v['median_relative_improvement'],2)+'%',f(100*v['central_95_draw_range'][0],2)+' to '+f(100*v['central_95_draw_range'][1],2)+'%',str(v['gain_exceeds_split_half_count'])+'/'+str(v['draws'])] for v in r['evaluation_sampling']['summary']]
p2.append(table('tab:p2sampling',r'Evaluation-sampling sensitivity for the same fixed field with 50 RK4 steps. For each cell count, 50 seeded draws sample source and target cells without replacement; prediction and unchanged-source comparisons use identical source indices and identical target indices within a draw. An additional pair of disjoint target subsets at that count defines a split-half reference. Percentages summarize relative improvement over unchanged source; the central 95\% draw range measures Monte Carlo sensitivity conditional on this cohort and field, not patient-level confidence. The final column counts draws whose gain exceeds the split-half reference. Cell count and resampling do not increase the three-donor biological sample size.',['Cells per distribution','Draws','Median improvement','Central 95% draw range','Gain exceeds reference'],rows,[34,17,37,42,37]))
d=json.loads((ROOT/'outputs/mathematical_audit/population/report.json').read_text())
rows=[[v['evaluation'],f"{v['n_source']} / {v['n_target']}",f(v['stay_still_distance'],5),f(v['predicted_distance'],5),f(100*v['relative_improvement'],2)+'%'] for v in d['evaluation']]
p2.append(table('tab:p2weights',r'Evaluation of the saved pooled 50-step field in training-standardized coordinates, using all 1,012 Wound1 and 3,821 Wound7 cells. ED is the double-precision weighted empirical energy distance, without subsampling. Cell-pooled weights are uniform; donor-balanced weights allocate one third to each donor and equal mass within donor. Predictions retain source weights. The final three rows evaluate training donors separately, not donor-transfer folds. Improvement uses the corresponding unchanged-source ED. These three-donor point estimates have no confidence intervals and differ from capped-distance estimates.',['Evaluation','Source / target cells','Stay-still ED','Predicted ED','Improvement'],rows,[40,37,31,31,28]))
(HERE/'tables.tex').write_text('\n\n'.join(p2)+'\n')
print('Exported supplementary numerical tables from reports without fitting models.')
